# Generated by Django 4.2.3 on 2023-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
