# Generated by Django 4.2.3 on 2023-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbook',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unitbook',
            name='children',
            field=models.IntegerField(),
        ),
    ]
