# Generated by Django 4.2.3 on 2023-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unit", "0007_unitbook_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitbook",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
