# Generated by Django 4.2.3 on 2023-08-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_alter_unitbook_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
    ]
