# Generated by Django 4.2.3 on 2023-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unit", "0009_alter_unit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitbook",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
