# Generated by Django 4.2.3 on 2023-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
