# Generated by Django 4.2.3 on 2023-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
