# Generated by Django 4.2.3 on 2023-08-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_services_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_page_image",
                to="settings.image",
            ),
        ),
    ]
