# Generated by Django 4.2.3 on 2023-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_address_alter_settings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address_2',
            field=models.CharField(default='Egypt', max_length=300),
        ),
    ]
