# Generated by Django 4.2.3 on 2023-08-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_settings_address_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(default="gg", max_length=250),
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(default="gg", max_length=150),
        ),
    ]
