# Generated by Django 4.2.3 on 2023-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_image_description_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
