# Generated by Django 4.2.3 on 2023-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_1", models.ImageField(upload_to="", verbose_name="about/")),
                ("image_2", models.ImageField(upload_to="", verbose_name="about/")),
                ("comments", models.TextField(max_length=500)),
            ],
        ),
    ]
